### PR TITLE
Bugfix: utf-8 multi-byte characters breaking diagnostic output

### PR DESCRIPTION
**Pull request by LiamPattinson**
Fixes https://github.com/PlasmaFAIR/fortitude/issues/197

Although I need to add a test to make sure...

### CODE REVIEW

**Comment by ZedThree** [comment]
Yeah, can you use the comment from the issue in a test? Or check with an emoji or something?

**Comment by ZedThree** [comment]
Weird that ruff doesn't need this here :shrug:

**Comment by LiamPattinson** [comment]
As Ruff is using the old version of `annotate-snippets`, maybe that worked on char ranges instead of byte ranges? It's hard to tell from the docs, as neither the old docs nor the new docs specify which they're using -- both just say it's a slice of `usize`.

**Comment by ZedThree** [comment]
Here's another example that fails (adjusting `S001.f90`):

```f90
program test
  use some_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_really_long_module_name, only : integer_working_precision
  implicit none
  integer(integer_working_precision), parameter, dimension(1) :: a = [1]
  write (*, '("╔════════════════════════════════════════════╗")')
  write (*, '("║  UTF-8 LOGO BOX                            ║")')
  write (*, '("╚════════════════════════════════════════════╝")')

end program test
```

**Pull request merged**
